### ISSUE TITLE
what two file systems? sentence missing

### ISSUE THREAD

**Issue by RossHyman** [rcc-uchicago/user-guide#10]
Hardware Overview/Midway3/File Systems second sentence "Both file systems..."  There is a sentence missing before this to introduce these two file systems. 
Also "Furthermore, the new storage system is designed that any file that is smaller than 4 KB in size will be bundled with the file metadata and stored on the pool of dedicated metadata SSDs that are part of the parallel storage system. " could be changed to "Furthermore, the new storage system is designed so that any file smaller than 4 KB will be bundled with the file metadata stored on the pool of dedicated metadata SSDs that are part of the parallel storage system. "

**Comment by jdlaurence** [comment]
I deleted the file systems section as it wasn't adding much, and am creating a new issue to note that this page overall needs a fairly substantial revision (as is noted in the markdown comments.)
