### ISSUE TITLE
How to propagate conda environment to the sinteractive session

### ISSUE THREAD

**Issue by aolykhin** [rcc-uchicago/user-guide#119]
This solution resolves the error:
ssh: symbol lookup error: ssh: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
https://rt.rcc.uchicago.edu/rt/Ticket/Display.html?id=55207

**Comment by ndtrung81** [comment]
@aolykhin FYI, the conflict in the openssl version between ssh and conda  can also be resolved by loading the python/anaconda module after getting an interactive session (search RT for tag openssl).

**Comment by aolykhin** [comment]
@ndtrung81 Yeah, I know about this, but it is not convenient to deactivate/activate the environment every time you start sinteractive. This way a user can follow the same pipeline with a little adjustment. Both solutions should be shared with users.
