### ISSUE TITLE
Complete Midway2/3 partition tables

### ISSUE THREAD

**Issue by jdlaurence** [rcc-uchicago/user-guide#12]
There is some missing information in the Midway2/3 partition and QOS tables (indicated by ?) on the midway_jobs_overview.md page.

**Comment by jdlaurence** [comment]
As per Ross and Trung,"At the moment, the gpu2 partition on midway2 has 6 nodes with K80 GPUs (midway2-gpu[01-06]) and 1 node with 2 V100 GPUs."

**Comment by aolykhin** [comment]
I'll take this one

**Comment by jdlaurence** [comment]
See #43 - majority of content added; still await confirmation on some info

**Comment by RossHyman** [comment]
some rows are duplicated and others have wrong information.

**Comment by jdlaurence** [comment]
Yeah, I'm working on an edit now

**Comment by RossHyman** [comment]
Maybe I'm just misreading it. The gpu partition for Midway 3 is listed twice because there are two kinds of gpus.  It isn't clear from this table that "--partition=gpu" can assign either gpu (at random?). But if you want a specific gpu then that can be specified too.

**Comment by jdlaurence** [comment]
good point. @aolykhin can you please add a note at the bottom or top of the top clarifying why certain partitions are repeated and (briefly) how to specifically request one?

**Comment by RossHyman** [comment]
Also, do these cost different amounts of units per hour or all they all the same?

**Comment by jdlaurence** [comment]
See https://rcc-uchicago.github.io/user-guide/midway23/midway_jobs_overview/
"In standard settings, 1 SU equals usage of 1 processing unit for 1 hour, but the exact calculation will vary depending on the amount of memory requested, as well as additional factors like the use of GPUs and CPU architecture. The aim of the Service Unit (SU) is to provide a “fair” account of computing resources."

**Comment by aolykhin** [comment]
@RossHyman @jdlaurence  Yeah, those are not duplicates, but different compute node configurations within the partitions. I believe you can request them by adding a constraint to sbatch  `--constraint=midway2-####` where the user provides the actual compute node name. The full list of names is available via sinfo command and I wanted to add this as it would make users life easier but then I realized that we don't have enough space and it would make a table ugly. For example, 164 nodes in broadwl partition are midway2-[0221-0279,0282-0299,0301,0312-0354,0356-0398].

**Comment by RossHyman** [comment]
By searching on slack, I see that for beagle3, the gpu nodes can be specified by a name. For a100: --constraint=a100, for v100: --constraint=a40. But I don't see anything indicating these names can be used for the midway3 gpu nodes.

**Comment by RossHyman** [comment]
rcchelp sinfo shared 
shows the only way to specify on Midway 3 is as Aleks says, through midway3-node_num. One day, when the systems team has the resources and hours, we can ask them to give intuitive names to the Midway 3 gpu nodes as in Beagle3 so it will be easier for users.

**Comment by jdlaurence** [comment]
@RossHyman This already exists here: https://rcc-uchicago.github.io/user-guide/midway23/examples/example_job_scripts/#gpu-jobs

(first result when searching "GPU"). But I take your point that it would be good to duplicate info on the partitions page. Again, I think it would be good for @aolykhin to add a small section about how to specify which nodes w/i a partition you are requesting.

**Comment by jdlaurence** [comment]
@aolykhin any updates on Midway2 partition info. Would be great to have on the partitions page by 1/24.

**Comment by aolykhin** [comment]
@jdlaurence Kathy responded partially about midway2 nodes. It seems that we need first need to get approval to advertise them

**Comment by aolykhin** [comment]
Shared partitions were updated
