### ISSUE TITLE
"How to write a good ticket" or "Help us help you" Section

### ISSUE THREAD

**Issue by himanshisyadav** [rcc-uchicago/user-guide#131]
Add a section to the user guide as well as the ticket submission form on writing informative tickets that make debugging the issue easier. 

Points to be included:
- Write an informative subject/title to the ticket (cluster name, software: brief issue) 
- CNetID
- Cluster Name (midway2, midway3, beagle3)
- How to reproduce the issue: command, error message etc

**Comment by ndtrung81** [comment]
@himanshisyadav can we close this issue with your recent PR #135?

**Comment by himanshisyadav** [comment]
Done! 👍
