### ISSUE TITLE
GPU's on Midway 2

### ISSUE THREAD

**Issue by RossHyman** [rcc-uchicago/user-guide#17]
In an email to Birali, Trung wrote "At the moment, the gpu2 partition on midway2 has 6 nodes with K80 GPUs (midway2-gpu[01-06]) and 1 node with 2 V100 GPUs." However, the new user guide reports only the K80's on Midway2 and not the V100 node.

**Comment by jdlaurence** [comment]
closing and adding a comment to the existing issue #12 about the various tables needing updating
