### ISSUE TITLE
accounts usage instructions incorrect for midway 3

### ISSUE THREAD

**Issue by RossHyman** [rcc-uchicago/user-guide#215]
Under allocations, account usage instructions are incorrect for midway 3.

accounts usage --byuser should be accounts -byuser (one dash not two. One dash and two dashes work for Midway 2)

accounts usage --byjob does not work on Midway 3 and accounts usage -byjob returns an error on Midway 3.

accounts usage --byjob and accounts usage -byjob both work for Midway 2.

**Comment by ndtrung81** [comment]
@RossHyman These are addressed in https://github.com/rcc-uchicago/user-guide/pull/214

**Comment by RossHyman** [comment]
Thanks
