### ISSUE TITLE
Hardware Overview

### ISSUE THREAD

**Issue by RossHyman** [rcc-uchicago/user-guide#36]
1. Standard Compute Nodes (Nodes repeated)
2. The 40 AMD nodes do not have the same specifications as the Intel nodes. The AMD nodes (according to information in the grants folder) have 128 cores per node and 256 GB of memory per node. (see below)
3. "Each big memory node."  instead of "The big memory node..."
4. replace 1 nodes with 1 node for each big memory node

According to the facilities description in the Gants Master folder the specifications for Midway2 and Midway3 are:

Midway3 HPC system
276 Intel 6248R compute nodes totaling 13248 cores and 53TB memory
5 Nvidia V100,  5 RTX6000 and 1 A100 (4 GPUs per node)
HDR Mellanox InfiniBand Interconnect. 
One node with 768 Gb of memory and one node with 1,536 GB of memory. 
40 AMD compute nodes with 128 cores per nodes and 256 GB of memory per node
2.3 PB of capacity storage using Spectrum Scale-GPFS parallel file system
Midway2
A total of 1,414 compute nodes including Intel E5-2680v4 processors 
Nvidia V100 GPU (4 GPUs per node), EDR Mellanox InfiniBand interconnect, and large shared-memory (up to 1536 GB of memory per node).
6.4 PB of  capacity storage using Spectrum Scale–GPFS parallel file system
Spectra Logic T950 Tape backup system with an uncompressed native capacity of 2.5PB  and capable of expanding to 10PB.
1.45 PB of cost-effective storage using ZFS parallel file system
Hadoop Cluster with 10 nodes and 160 TB HDFS file system. .

There are several differences between what is listed here and what is listed in the new RCC user guide. In particular for Midway 3, the 40 AMD nodes do not have the same specifications as the Intel nodes. The AMD nodes are said to have 128 cores per node and 256 GB of memory per node.

Also, the total number of nodes is very different. I am assuming that the reason that the facilities page lists a larger number of nodes is that it includes nodes that are reserved for specific use such as Beagle3 and the smaller numbers quoted in the user guide are the correct number to state because these are the ones that are available to all user.

**Comment by jdlaurence** [comment]
updated page to reflect this
