### ISSUE TITLE
Connecting to Midway

### ISSUE THREAD

**Issue by RossHyman** [rcc-uchicago/user-guide#37]
Connecting to Midway

1. Hyperlink to RCC user policy broken
2. Remove explicit reference to midway3-login1 etc to discourage people logging in this way.
3. XQuartz is not working for me on my 2022 macbook pro. Don't know if it is something I did wrong or if XQuartz is incompatible with newer Macs.  Need to find Xaquartz replacement.
4. The screen pictures at The Thinklinc Interface are not for Thinklinc in current Midway 3. 
5. Remote Visualization on midway2: Is this not needed for midway 3?

**Comment by jdlaurence** [comment]
fixed 1-2, 3-5 still need attention

**Comment by jdlaurence** [comment]
I'm going to resolve this issue and open two new ones specifically focused on 3) and 4)
