### ISSUE TITLE
Data Storage

### ISSUE THREAD

**Issue by RossHyman** [rcc-uchicago/user-guide#40]
Project Directories
where <PI CnetID> is the....   ( <Pi CnetID> missing)
Cost-Effective Data Storage
through the Cluster Partnership Program ('the" is missing) 

Why do we include the sentences about (mode 0700) and (mode 2770)? Can we cut them?

**Comment by jdlaurence** [comment]
I addressed the typo. I don't think we should cut the permissions statement, it's good to know.

**Comment by RossHyman** [comment]
Yes. Buy they are not introduced until the next section, where they are fully covered.
