### ISSUE TITLE
Software

### ISSUE THREAD

**Issue by RossHyman** [rcc-uchicago/user-guide#41]
Software
First sentence should be changed to refer to Midway3. Also link broken

Running Applications from ThinLinc by Clicking Application Icons (Midway3 Only)
I believe that the very first subsection under software should be Running Application in Thinlinc.  Many of the most commonly used applications are available by clicking applications in Thinlinc and then clicking the the box with nine small squares.  The user can click on an application icon just like they do in a Windows or Mac system.  What these actually do is run a script to module load the application and then run it on the log-in node. These icons do not exist on Midway2.

Python and Jupyter Notebook
I believe the section on Jupyter Notebook should be changed to match that of other applications like Matlab and Mathematica. we do not need to teach anything about piping etc. Everything works inside Thinlinc.

Using Jupyter Notebook

To use Jupyter Notebook's Firefox browser interface on Midway, we recommend connecting to Midway via ThinLinc.

To use Jupyter Notebook on a log-in node, click the Jupyter Notebook icon in the application window. Alternatively you can click on the terminal icon and type.

module load python
jupyter notebook

A Jupyter notebook will open up in a Firefox browser window inside Thinlinc. 

In order to run Jupyter in a Firefox browser window on a compute node, click on the terminal icon and issue the above commands preceded by sinteractive: 

sinteractive --account=pi-\<PI CnetID\>
module load python
jupyter notebook

**Comment by pcarbo** [comment]
@RossHyman Have you tried jupyter notebook with the `--ip` option? It is 100x times better than using it inside thinlinc. We should not be encouraging using jupyter notebook inside thinlinc.

**Comment by RossHyman** [comment]
Why? We do it for all of the other applications.

**Comment by pcarbo** [comment]
Most RCC users do not use ThinLinc.
It should be avoided when possible.

**Comment by RossHyman** [comment]
Are you sure?

Plenty of university hpc's encourage people to use application, including juoyternotebook, through Thinlinc or Open on Demand.  For example:  https://hpc.nmsu.edu/discovery/ondemand/jupyter-notebook/

**Comment by pcarbo** [comment]
Yes, I'm sure.

**Comment by RossHyman** [comment]
I think we have an obligation to make things as easy as possible for people. If it is true that Thinklinc is too slow then we should switch to something faster so that the user experience that people have grown accustomed to with Windows and Macs can carry over to their use of Midway.

**Comment by pcarbo** [comment]
I'm just reporting how users actually use midway2 and midway3 in practice.

**Comment by pcarbo** [comment]
ThinLinc is a useful tool for some users, but to be clear the majority of users do not use it, and do not need it, nor do they need an alternative.

The larger point is that people use midway2 and midway3 in different ways, and we should support their different approaches.

**Comment by RossHyman** [comment]
The user guide recommends using thinlinc for R, Matlab, and Mathematica.

**Comment by RossHyman** [comment]
I'll concede that we should include how to do piping to run Jupyter notebook on a local browser. But we should also first teach the easier way of just running it inside thinlinc as we recommend for Matlab and Mathematica.

**Comment by pcarbo** [comment]
The axis is not easy vs. hard. It is more about what types of things people are doing, and finding the set of tools and interfaces that best fit their needs. So I see using ThinLinc has one option to consider along with a menu of other options.

**Comment by jdlaurence** [comment]
I fixed the initial Midway2 typo, and agree that there could be more information/a dedicated page for ThinLinc use. But I also agree with @pcarbo that we shouldn't be encouraging it too much, especially for jupyter. I've labeled this "minor addition"

**Comment by jdlaurence** [comment]
I'm going to close this issue as it's now addressed in #46
