### ISSUE TITLE
Instructions for HTML data transfer incorrect or unclear

### ISSUE THREAD

**Issue by RossHyman** [rcc-uchicago/user-guide#53]
The instructions say that "RCC provides web access to data on their storage system via public_html directories in users’ home directories." However, there is no public_html directory in the Midway2 or Midway3 home directories. There is a directory called Public. Should public_html be changed to Public in the user guide instructions? Or is the user expected to create a directory called public_html. If so, the instructions should explain that. I have not followed through on the rest of the instructions to see if they work.

**Comment by pnsinha** [comment]
Currently, web access is only available in midway2. Create a public_html directory under home if it does not exist already. Here are the instructions: https://rcc.uchicago.edu/docs/data-transfer/index.html#http-web-access.

**Comment by jdlaurence** [comment]
I adding clarifying text to the section
