### ISSUE TITLE
Instructions added to the README file for contributing/modifying to doc pages

### ISSUE THREAD

**Issue by ndtrung81** [rcc-uchicago/user-guide#6]
I propose that we add a paragraph or two showing how to submit PRs: git pull at main, git checkout a new branch, make some changes, commit the changes, push the branch, and create a new PR.

**Comment by jdlaurence** [comment]
This is a great idea.

**Comment by jdlaurence** [comment]
@ndtrung81 I have edited the readme to provide a skeleton of this process. Would you be open to adding more detail? (Or giving your opinion on its current state)?

**Comment by ndtrung81** [comment]
Thanks, @jdlaurence Looks good, and I have just submitted a PR for minor edits. Let's close this one for now.
