### ISSUE TITLE
add info about rclone on transferring files b/ midway and clouds

### ISSUE THREAD

**Issue by aolykhin** [rcc-uchicago/user-guide#77]
https://rt.rcc.uchicago.edu/rt/Ticket/Display.html?id=52373

**Comment by pcarbo** [comment]
@aolykhin I don't know if we should be officially advertising rclone; previous Systems Team people had concerns about widespread use.

**Comment by jdlaurence** [comment]
Yes, I think globus, samba, and scp are our officially supported data transfer mechanisms. I'll close this for now
