### ISSUE TITLE
elaborate quota

### ISSUE THREAD

**Issue by aolykhin** [rcc-uchicago/user-guide#78]
Hi Jose,

Please determine if the user or group quota is exceeded by running: rcchelp quota.

You can meet user quota (1-3) or group quota (1-5) by following the steps listed below:

1. Remove unused data to meet quota requirements. If the group quota is exceeded, consider removing former users' directories if they are large. You need to let us know the path to folders you don't have permission to remove and ask PI to respond to this thread with approval.

2. Temporary solution: move files to /scratch with a higher quota limit. Note that /scratch is not backed up, and you should not use it for long-term storage.

3. Move files to another storage. It could be a local machine or a cloud. See the data transfer section in the new user guide we are working on: https://rcc-uchicago.github.io/user-guide/midway23/midway_data_transfer/

4. Ask PI to submit a research allocation request to get more storage (If standard research allocation is not enough - special research allocation can give temporary storage of a greater size) https://rcc.uchicago.edu/accounts-allocations/request-allocation

5. Ask PI to purchase storage via the cluster partnership program: https://rcc.uchicago.edu/support-and-services/cluster-partnership-program

Best,

Aleks

**Comment by aolykhin** [comment]
also https://rt.rcc.uchicago.edu/rt/Ticket/Display.html?id=52803

**Comment by jdlaurence** [comment]
done
