### ISSUE TITLE
add info about gaussian and gaussview

### ISSUE THREAD

**Issue by aolykhin** [rcc-uchicago/user-guide#79]
https://rt.rcc.uchicago.edu/rt/Ticket/Display.html?id=34619

**Comment by pcarbo** [comment]
I would be careful about adding info about gaussian access — it may go against gaussian's usage restrictions.

**Comment by jdlaurence** [comment]
Given Pete's comment the fact that we don't currently support avogadro or gaussview on Midway3, I'm going to close this issue for now.
