### ISSUE TITLE
Broken link on "Connecting to Midway"

### ISSUE THREAD

**Issue by imiro** [rcc-uchicago/user-guide#80]
There is a broken link on the [Connecting to Midway](https://rcc-uchicago.github.io/user-guide/midway23/midway_connecting/) page: the link [Running Jobs on Midway](https://rcc-uchicago.github.io/midway23/midway_jobs_overview) inside the Warning box has incorrect link when rendered on github pages.

Changing the link on the markdown file from `/midway23/midway_jobs_overview` to `../midway_jobs_overview` may be able to solve this.

**Comment by jdlaurence** [comment]
Fixed! thank you
