### ISSUE TITLE
Add an alternate solution for accessing Jupyter Notebooks until --ip solution is not operational

### ISSUE THREAD

**Issue by himanshisyadav** [rcc-uchicago/user-guide#81]
Current Solution: 
/sbin/ip route get 8.8.8.8 | awk '{print $7;exit}'
jupyter-notebook --no-browser --ip=<ip address> --port=15000
Go to the URL generated by the above command

Alternate Solution while the above solution is not working:
jupyter notebook --no-browser --port=8080 
ssh -L 8080:localhost:8080 hyadav@midway3.rcc.uchicago.edu
Connect to URL:http://localhost:8080/ from local machine's browser.

**Comment by jdlaurence** [comment]
@ndtrung81 updated this, so I'll close this issue

**Comment by pcarbo** [comment]
The instructions tell you to this for both midway2 and midway3:

```bash
ssh -N -f -L 15021:midway3-login3:15021 [your-CNetID]@midway3.rcc.uchicago.edu
```

But we should be clear this only works if you are running jupyter notebook from midway3-login3!

**Comment by jdlaurence** [comment]
@pcarbo would you be able to fix this?
