### ISSUE TITLE
Can not open Firefox and cannot specify the login node

### ISSUE THREAD

**Issue by xsun1229** [rcc-uchicago/user-guide#86]
Hi,

I have two questions about connecting midway2 with thinlinc. 

1. 
I am trying to open Firefox with ThinLinc but I am getting an error, as shown in the screenshot below:
<img width="894" alt="Screen Shot 2023-02-16 at 10 00 39 AM" src="https://user-images.githubusercontent.com/62573051/219421524-e30cd456-5bb7-4941-834f-85ee8ff7f5f5.png">

I have already killed all my ThinLinc processes with the following commands:

```
$ echo $HOSTNAME
 midway2-login1.rcc.local
$ ps -ef | grep thin | grep sxt1229 | awk '{print $2}'
20085
20385
20579
22634
$ kill -9 <id>
```

Do you have any suggestions on how to resolve this error?

2. 
When I try to connect to Midway2 using ThinLinc, I always fail to specify the login node. When I specify a login node using https://midway2-login1.rcc.uchicago.edu/main/agent, it always switches to another login node, https://midway2-login2.rcc.uchicago.edu/main/agent, and vice versa. Do you have any solutions to this issue?

Thank you! 
Xiaotong

**Comment by ndtrung81** [comment]
@xsun1229 please submit a ticket to the Help Desk for these questions. Issues that are only related to the details of the User Guide are open here.
