### ISSUE TITLE
info about -f flag (inlc. gdal module after slurm update)

### ISSUE THREAD

**Issue by aolykhin** [rcc-uchicago/user-guide#87]
https://rt.rcc.uchicago.edu/rt/Ticket/Display.html?id=51714

**Comment by pcarbo** [comment]
The -f flag is needed for many modules not just the gdal module.

**Comment by jdlaurence** [comment]
noting that -f is for --force; "A modulefile will be loaded even if it comes in conflict with another loaded modulefile or that a modulefile will be unloaded even if it is required as a prereq by another modulefile."

**Comment by jdlaurence** [comment]
fixed in #102
