### ISSUE TITLE
Old links to docs and tutorials are broken

### ISSUE THREAD

**Issue by afarah18** [rcc-uchicago/user-guide#94]
Hi! I'm trying to access an old tutorial that used to live at https://rcc.uchicago.edu/docs/tutorials/intro-to-rcc-KICP.html and still shows up on google when I search "kicp rcc partition" but if I try to enter that url into my browser, I get redirected to the home page https://rcc-uchicago.github.io/user-guide/ every time. I've tried searching for tutorials on the new website but am unable to find any. Is there a way to link to the legacy site for these docs?

**Comment by jdlaurence** [comment]
@afarah18 Thanks for raising this! We'll get KICP info on the new site asap!

**Comment by jdlaurence** [comment]
@afarah18 You will now find the content from the old tutorial pages in the new tutorial section of the guide!

**Comment by afarah18** [comment]
Thank you! Just a note that the old webpage (https://rcc.uchicago.edu/docs/tutorials/intro-to-rcc-KICP.html) still shows up on a google search but redirects to the main user guide page (https://rcc-uchicago.github.io/user-guide/) rather than the tutorials page, but I suspect it will just take some time for the new tutorials page to show up on google search :)
